config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'genres/products'
  end
  get 'admins/top'
  # 管理者ログイン・サインインのコントローラとして管理者用作成したコントローラを指定
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  get 'admin_products/new'
  get 'admin_products/index'
  get 'admin_products/create'
  get 'admin_products/show'
  get 'admin_products/edit'
  get 'admin_products/update'
  get 'new/create'
  get 'new/show'
  get 'new/edit'
  get 'new/update'

  # 会員ログイン・サインインのコントローラとして会員用作成したコントローラを指定
    devise_for :members, controllers: {
        sessions:      'members/sessions',
        passwords:     'members/passwords',
        registrations: 'members/registrations'
    }

  get 'members/show'
  get 'members/edit'
  get 'members/update'
  # devise_for :members

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  get 'home/about' => 'homes#about'
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' => 'members#withdraw', as: 'withdraw' #会員退会用メソッド
  delete 'cart_products' => 'cart_products#destroy_all'
  get 'members/:id/orders/input' => 'orders#input', as: 'input'
  post 'members/:id/orders/new' => 'orders#new', as: 'new'
  get 'members/:id/orders/new' => 'orders#new', as: 'new_order'
  get 'orders/thanks' => 'orders#thanks'
  get 'admins/top' => 'admins#top'

  resources :members, only: [:show, :edit, :update]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resources :cart_products, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create]
  resources :products, only: [:index, :show]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_products, only: [:update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :member
	belongs_to :product

	validates :count, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :products, dependent: :destroy
    accepts_attachments_for :products, attachment: :product_image
    validates :name, presence: true
    validates :status,  inclusion: {in: [true, false]}
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :shipping_addresses, dependent: :destroy
	has_many :orders #memberを削除した時に注文履歴は消えてはいけないのでdependent: :destroyは書いてないです
	has_many :products, dependent: :destroy,through: :cart_products

	enum status: {有効: 0, 退会済: 1}
	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	def address_name
		self.first_name + self.last_name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_products, dependent: :destroy

	enum payment:{クレジットカード: 0, 銀行振込: 1}
	enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order,optional: true
	belongs_to :product

	enum status:{着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/models/product.rb
class Product < ApplicationRecord

	has_many :members, dependent: :destroy,through: :cart_products
	has_many :order_products, dependent: :destroy

	belongs_to :genre
	attachment :product_image
	enum status:{	販売中:	0,売り切れ:	1 }
	validates :name, presence: true
	validates :text, presence: true
    validates :price, presence: true
	validates :status, presence: true
	validates :genre_id, presence: true
    validates :product_image, presence: true

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :member

	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	validates :address, presence: true
	validates :address_name, presence: true

	def shippinng
		self.postal_code + self.address + self.address_name
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
	def index
		@cart_products = CartProduct.where(member_id:current_member)

		@total_price = 0
		@cart_products.each do |cart_product|
			@total_price += cart_product.product.price * cart_product.count
		end
	end
	def create
		@cart_product = CartProduct.new(cart_product_params)
		@cart_product.member_id = current_member.id
		@product = Product.find(params[:cart_product][:product_id])
		@cart_product.product_id = @product.id
		if @cart_product.count != 0 && @cart_product.save
			redirect_to cart_products_path
		else 
			redirect_to product_path(@product)
		end
	end
	def update
		@cart_product = CartProduct.find(params[:id])
		@cart_product.update(cart_product_params)
		redirect_to cart_products_path
	end
	def destroy
		@cart_product = CartProduct.find(params[:id])
		@cart_product.destroy
		redirect_to cart_products_path
	end
	def destroy_all
		@cart_products = CartProduct.all
		@cart_products.destroy_all
		redirect_to cart_products_path
	end

	private
	def cart_product_params
		params.require(:cart_product).permit(:count, :member_id, :product_id)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


	def top
		@products = Product.where(status:"販売中").page(params[:page]).reverse_order
		@genres = Genre.all
	end

	def about
	end

end

app/helpers/admin_genres_helper.rb
module AdminGenresHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_orders_helper.rb
module AdminOrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_products/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <h2>ショッピングカート</h2>
      </div>
      <div class = "col-xs-offset-5 col-xs-2 destroy-btn">
        <%= link_to "カートを空にする", cart_products_path, method: :delete,class: "btn btn-danger", "data-confirm" => "本当に削除しますか-？" %>
      </div>
    </div>
    <!-- カート内商品一覧 -->
      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">
          <table class = "table table-bordered table-inverse">
            <thead>
              <tr class="info">
                <th width = "300" class="text-center">商品名</th>
                <th width = "100" class="text-center">単価(税込)</th>
                <th width = "100" class="text-center">数量</th>
                <th width = "100" class="text-center">小計</th>
                <th width = "100" class="text-center"></th>
              </tr>
            </thead>
            <tbody>
          
            <% @cart_products.each do |cart_product| %>
              
                <tr>
                  <td><%= attachment_image_tag cart_product.product, :product_image,format:'jpeg',size: "50x50" %><%= cart_product.product.name %></td>
                  <td class="text-center"><%= (cart_product.product.price * 1.1).floor %></td>
                  <td class="text-center">
                    <%= form_for(cart_product) do |f| %>
                      <%= f.text_field :count, :size=>"5" %>
                      <%= f.hidden_field :id %>
                      <%= f.submit "変更",class: "btn btn-info btn-sm" %>
                      </a>
                    <% end %>
                  </td>

                  <td class="text-center"><%= (cart_product.product.price * 1.1 * cart_product.count).floor %></td>
                  <td class="text-center"><%= link_to "削除する", cart_product_path(cart_product.id), method: :delete,class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
                </tr>
             
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <!-- /カート内商品一覧 -->

      <div class="row">
        <div class="col-xs-offset-1 col-xs-2">
          <a class = "show-icon">
          <%= link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
          </a>
        </div>
        <div class="col-xs-offset-4 col-xs-4">
          <table class = "table table-bordered table-inverse">
            <tr>
              <th class="info">合計金額</th>
              <td><%= (@total_price * 1.1).floor %></td>
            </tr>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-offset-4 col-xs-4">
            <%= link_to "情報入力に進む", input_path(current_member),class: "btn btn-success btn-lg center-block" %>
        </div>
      </div>

  </div>
</div>