config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'genres/products'
  end
  get 'admins/top'
  # 管理者ログイン・サインインのコントローラとして管理者用作成したコントローラを指定
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  get 'admin_products/new'
  get 'admin_products/index'
  get 'admin_products/create'
  get 'admin_products/show'
  get 'admin_products/edit'
  get 'admin_products/update'
  get 'new/create'
  get 'new/show'
  get 'new/edit'
  get 'new/update'

  # 会員ログイン・サインインのコントローラとして会員用作成したコントローラを指定
    devise_for :members, controllers: {
        sessions:      'members/sessions',
        passwords:     'members/passwords',
        registrations: 'members/registrations'
    }

  get 'members/show'
  get 'members/edit'
  get 'members/update'
  # devise_for :members

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  get 'home/about' => 'homes#about'
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' => 'members#withdraw', as: 'withdraw' #会員退会用メソッド
  delete 'cart_products' => 'cart_products#destroy_all'
  get 'members/:id/orders/input' => 'orders#input', as: 'input'
  post 'members/:id/orders/new' => 'orders#new', as: 'new'
  get 'members/:id/orders/new' => 'orders#new', as: 'new_order'
  get 'orders/thanks' => 'orders#thanks'
  get 'admins/top' => 'admins#top'

  resources :members, only: [:show, :edit, :update]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resources :cart_products, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create]
  resources :products, only: [:index, :show]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_products, only: [:update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
	belongs_to :member
	belongs_to :product

	validates :count, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :products, dependent: :destroy
    accepts_attachments_for :products, attachment: :product_image
    validates :name, presence: true
    validates :status,  inclusion: {in: [true, false]}
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :shipping_addresses, dependent: :destroy
	has_many :orders #memberを削除した時に注文履歴は消えてはいけないのでdependent: :destroyは書いてないです
	has_many :products, dependent: :destroy,through: :cart_products

	enum status: {有効: 0, 退会済: 1}
	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	def address_name
		self.first_name + self.last_name
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :member
	has_many :order_products, dependent: :destroy

	enum payment:{クレジットカード: 0, 銀行振込: 1}
	enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order,optional: true
	belongs_to :product

	enum status:{着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/models/product.rb
class Product < ApplicationRecord

	has_many :members, dependent: :destroy,through: :cart_products
	has_many :order_products, dependent: :destroy

	belongs_to :genre
	attachment :product_image
	enum status:{	販売中:	0,売り切れ:	1 }
	validates :name, presence: true
	validates :text, presence: true
    validates :price, presence: true
	validates :status, presence: true
	validates :genre_id, presence: true
    validates :product_image, presence: true

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
	belongs_to :member

	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	validates :address, presence: true
	validates :address_name, presence: true

	def shippinng
		self.postal_code + self.address + self.address_name
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_action :authenticate_admin!
  def new
    @admin_product = Product.new

    @genres = Genre.where(status: 'true')


  end

  def index
    @admin_products = Product.all
    
    
  end

  def create
    @admin_products = Product.all
    @admin_product = Product.new(params_admin_product)
    if @admin_product.save!
      redirect_to admin_product_path(@admin_product)
    else
      render :new
    end
  end

  def show
    @admin_product = Product.find(params[:id])
  end

  def edit
    @genres = Genre.where(status: 'true')

    @admin_product = Product.find(params[:id])
  end

  def update
    @admin_product = Product.find(params[:id])
    @admin_product.update(params_admin_product)
    if @admin_product.save
      redirect_to admin_product_path
    else
      render :edit
    end
  end

  private

  def params_admin_product
    params.require(:product).permit(:name, :text, :genre_id, :price,:status,:product_image)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


	def top
		@products = Product.where(status:"販売中").page(params[:page]).reverse_order
		@genres = Genre.all
	end

	def about
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@genres = Genre.all
		@genre = Genre.find(params[:id])
		@products = @genre.products.where(status:"販売中").page(params[:page]).reverse_order
	end
	def show
		@genres = Genre.all

		@cart_product = CartProduct.new
		@admin_product = Product.find(params[:id])
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin_genres_helper.rb
module AdminGenresHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_orders_helper.rb
module AdminOrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class ="container">
  <div class ="row this">
    <h3 class ="title">商品編集画面</h3>
    <%= form_for(@admin_product ,url: admin_product_path) do |f| %>
    <div class = "col-xs-3">
      <%=  attachment_image_tag @admin_product, :product_image,format:'jpeg',size: "90x90"%>
      <%= f.attachment_field :product_image%>
    </div>
    <div class ="col-xs-5">
      <table>
      <tr>
        <th><%= f.label :name, "商品名", class:"title" %></th>
        <td><%= f.text_field :name, class:"body" %></td>
      </tr>
      <tr>
        <th><%= f.label :text, "商品説明", class:"title" %></th>
        <td><%= f.text_area :text, class:"body" %></td>
      </tr>
      <tr>
        <th><%= f.label :genre_id, "ジャンル", class:"title" %></th>
        <td><%= f.collection_select :genre_id, @genres, :id, :name, class:"body" %></td>
      </tr>
      <tr>
        <th><%= f.label :price, "税抜き価格", class:"title" %></th>
        <td><%= f.text_field :price, class:"body"%></td>
      </tr>
      <tr>
        <th><%= f.label :status, "販売ステータス", class:"title" %></th>
        <td><%= f.select :status, Product.statuses.keys{}, class:"body"%></td>
      </tr>
      </table>
      <div class ="pull-right">
        <%= f.submit "変更内容を保存", class:"btn btn-info" %>
      </div>
    <%end%>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class = "container">
<div class = "row">
  <div class="col-xs-offset-1 col-xs-9">
    <div class="page-info"><h2 class="paroducts-title">商品一覧画面
        <%=link_to new_admin_product_path do %>
          <span class ="image"><%= image_tag "plus.jpeg",size: "40x40"%></span>
        <%end%>
    </h2></div>
  </div>
</div>
<div class="row">
  <div class="col-xs-offset-1 col-xs-10">
      <table class= "table table-bordered text-center">
        <thead>
          <tr bgcolor="#f5f5f5">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @admin_products.each do |admin_product|%>
          <tr>
            <td><%=admin_product.id%></td>
            <td>
              <%= link_to admin_product_path(admin_product.id) do %>
                <%=admin_product.name%>
              <% end %>
            </td>
            <td><%=admin_product.price%></td>
            <td><%=admin_product.genre.name%></td>
            <td><%=admin_product.status%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class = "container">
  <div class = "row">
<h1 class = "title">商品　新規登録画面</h1>


<%= form_for(@admin_product ,url: admin_products_path) do |f| %>
  <div class = "col-xs-4">
    <p><%= f.attachment_field :product_image%>
    </p>
  </div>
 
  <div class = "col-xs-5">
  <table>
  <tr>
    <td><p><%= f.label :name, "商品名",class:"colum"%></td>
    <td><%= f.text_field :name%></p></td>
  </tr>
  <tr>
      <td><p><%= f.label :text, "商品説明",class:"colum"%></td>
        <td><%= f.text_area :text %></p></td>
  </tr>
  <tr>
    <td><p><%= f.label :genre_id, "ジャンル",class:"colum" %></td>
    <td><%= f.collection_select :genre_id, @genres, :id, :name %></p></td>
  </tr>
  <tr>
    <td><p><%= f.label :price, "税抜き価格",class:"colum" %></td>
      <td><%= f.text_field :price%></p></td>
  </tr>
  <tr>
    <td><p><%= f.label :status, "販売ステータス",class:"colum"%></td>
      <td><%= f.select :status, Product.statuses.keys{}%></p></td>
  </tr>
</table>
    <%= f.submit "新規登録",class: "index btn btn-info" %>
  </div>
</div>
</div>
<%end%>

app/views/admin/products/show.html.erb
<div class ="container">
  <div class = "row this">
    <h3>商品詳細画面</h3>
    <div class = "col-xs-3 float-left">
    <p><%=  attachment_image_tag @admin_product, :product_image,format:'jpeg',size: "90x90"%></p>
    </div>
    <div class ="col-xs-6 float-left">
    <table>
    <tr>
      <th><%=label :name, "商品名",class:"column-name"%></th>
      <td><%= @admin_product.name%></td>
    </tr>
    <tr>
      <th><%=label :text, "商品説明",class:"column-name"%></th>
      <td><%= @admin_product.text%></td>
    </tr>
    <tr>
      <th><%=label :genre_id, "ジャンル",class:"column-name"%></th>
      <td><%= @admin_product.genre.name%></td>
    </tr>
    <tr>
      <th><%=label :price, "税込価格(税抜き価格)",class:"column-name"%></th>
      <td><%= (@admin_product.price*1.1).floor%>(<%= @admin_product.price %>)</td>
    </tr>
    <tr>
      <th><%=label :status, "販売ステータス",class:"column-name"%></th>
      <td><%= @admin_product.status%></td>
    </tr>
    </table>
  </div>
  <div class ="float-left text-center edit">
    <p><%= link_to "編集する",edit_admin_product_path(@admin_product.id),class:"btn btn-info"%></p>
  </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <!-- ジャンル部分テンプレート -->
      <div class="col-xs-2 genre-box">
        <h3 class="genre-search-title text-center">ジャンル検索</h3>
        <div class="genre-link">
          <% @genres.each do |genre| %>
          <%= link_to genre.name,products_path(id: genre.id) %><br>
          <% end %>
        </div>
      </div>

      <!-- 商品一覧ページ -->
      <div class="col-xs-10">
<<<<<<< HEAD
        <h2>ケーキ (全<%= @products.count %>件)</h2>
        <div>
<<<<<<< HEAD
<<<<<<< HEAD
          <% @products.each do |product| %>
            <ul>
              <li>画像<%= link_to adimin_product_path(product.id) do %>
                  <%= attachment_image_tag product, :product_image, :fill, 100, 120, format: 'jpeg' %>
                <% end %>
=======
          <% @admin_products.each do |admin_product| %>
=======
          <% @products.each do |admin_product| %>
>>>>>>> fe23d3eeeff92a75ac3878e1f9fbf715c88c48b4
            <ul>
              <li>
                <div>
                  <%= link_to product_path(admin_product.id) do %>
                    <%= attachment_image_tag admin_product, :product_image,format:'jpeg',size: "90x90" %>
                <% end %>
                </div>
                <div><%= admin_product.name %></div>
                <div>￥<%= admin_product.price %></div>
>>>>>>> 6c8281cddfb65eea788462d40d91eb3be893974b
              </li>
              <li>商品名<%= product.name %></li>
              <li>価格<%= product.price %></li>
            </ul>
=======
        <h2><%= @genre.name %> (全<%= @products.count %>件)</h2>
        <div class="product-box">
          <% @products.each do |product| %>
            <div class="product-item clearfix">
              <div class="product-image">
                  <%= link_to product_path(product.id) do %>
                    <%= attachment_image_tag product, :product_image,format:'jpeg',size: "200x150" %>
                <% end %>
                </div>
              <div class="product-details">
                <p class="product-name">商品名：<%= product.name %></p>
                <p class="product-price">¥<%= product.price %></p>
                <span class="product-genre"><%= link_to product.genre.name,products_path(id: product.genre.id) %>
                </span>
              </div>
            </div>
>>>>>>> 0aeb92afd53a1d33ab328e48cb1c9d4bedbc46b9
          <% end %>
          <%= paginate @products, class: "paginate" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <!-- ジャンル部分テンプレート -->
      <div class="col-xs-2 genre-box">
        <h3 class="genre-search-title text-center">ジャンル検索</h3>
        <div class="genre-link">
          <% @genres.each do |genre| %>
          <%= link_to genre.name,products_path(id: genre.id) %><br>
          <% end %>
        </div>
      </div>

      <!-- 商品詳細ページ -->
      <div class="product-show">
          <div class="col-xs-offset-1 col-xs-3">
            <%= attachment_image_tag @admin_product, :product_image,format:'jpeg',size: "200x200", class: "product-img" %>
          </div>
          <div class="col-xs-5">
            <h2 class="product-name"><%= @admin_product.name %></h2>
            <p class="product-text"><%= @admin_product.text %></p>
            <h4 class="price"><%= number_to_currency(@admin_product.price * 1.1, unit: "￥", strip_insignificant_zeros: true) %> (税込)</h4>

            <%= form_for(@cart_product,:url => {controller: "cart_products", :action => :create}) do |f|  %>
              <%= f.text_field :count, placeholder:"個数を入力",class: "count" %>
              <%= f.hidden_field :product_id, :value => @admin_product.id %>
              <%= f.submit "カートに入れる", class: "btn btn-primary" %>
            <% end %>

          </div>

    </div>
  </div>
</div>