config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'genres/products'
  end
  get 'admins/top'
  # 管理者ログイン・サインインのコントローラとして管理者用作成したコントローラを指定
    devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  get 'admin_products/new'
  get 'admin_products/index'
  get 'admin_products/create'
  get 'admin_products/show'
  get 'admin_products/edit'
  get 'admin_products/update'
  get 'new/create'
  get 'new/show'
  get 'new/edit'
  get 'new/update'

  # 会員ログイン・サインインのコントローラとして会員用作成したコントローラを指定
    devise_for :members, controllers: {
        sessions:      'members/sessions',
        passwords:     'members/passwords',
        registrations: 'members/registrations'
    }

  get 'members/show'
  get 'members/edit'
  get 'members/update'
  # devise_for :members

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  get 'home/about' => 'homes#about'
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' => 'members#withdraw', as: 'withdraw' #会員退会用メソッド
  delete 'cart_products' => 'cart_products#destroy_all'
  get 'members/:id/orders/input' => 'orders#input', as: 'input'
  post 'members/:id/orders/new' => 'orders#new', as: 'new'
  get 'members/:id/orders/new' => 'orders#new', as: 'new_order'
  get 'orders/thanks' => 'orders#thanks'
  get 'admins/top' => 'admins#top'

  resources :members, only: [:show, :edit, :update]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resources :cart_products, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :show, :create]
  resources :products, only: [:index, :show]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_products, only: [:update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :shipping_addresses, dependent: :destroy
	has_many :orders #memberを削除した時に注文履歴は消えてはいけないのでdependent: :destroyは書いてないです
	has_many :products, dependent: :destroy,through: :cart_products

	enum status: {有効: 0, 退会済: 1}
	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	def address_name
		self.first_name + self.last_name
	end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
before_action :authenticate_admin!

	def index
		@members = Member.all

	end

	def show
		@member = Member.find(params[:id])
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update
		@member = Member.find(params[:id])
		@member.update(member_params)
		redirect_to admin_member_path(@member.id)
	end

	private
	def member_params
  	params.require(:member).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone, :status)
	end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone, :status])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone, :status])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  # redirect_to root_path
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
   before_action :logout_status, only:[:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #  redirect_to root_path
  # end

  #def after_sign_in_path_for(resource)
   # redirect_to root_path
  #end

  # protected

  def logout_status
    @user = Member.find_by(email: params[:member][:email], status: "退会済")
    if @user
      flash[:withdraw] = '退会済みのアカウントです'
      redirect_to new_member_session_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
 #  end

end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
    if @member != current_member
      redirect_to member_path(current_member)
    end
  end

  def edit
    @member = Member.find(params[:id])
    if @member != current_member
      redirect_to member_path(current_member)
    end
  end

  def update
  	@member = Member.find(params[:id])
  	@member.update(member_params)
    redirect_to member_path(@member.id)
    if @member != current_member
      redirect_to member_path(current_member)
    end
  end

  def delete_me
  	@member = Member.find(params[:id])
  end

  def withdraw
    @member = Member.find(params[:id])
    @member.status = 1
    @member.save

    #pry-byebug
    sign_out

    redirect_to root_path
  end

  private
  def member_params
  	params.require(:member).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone, :status)
  end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/delete_me.html.erb
<div class="row">

		<h3 class="text-danger text-center">本当に退会しますか？</h3>

	<p class="text-center">退会すると、会員登録情報や<br>
	これまでの購入履歴が閲覧できなくなります。<br>
	退会する場合は、「退会する」をクリックしてください。</p><br>

		<center>
			<%= link_to "退会しない", member_path(@member.id),class: "btn btn-info" %>
			<%= link_to "退会する", withdraw_path, method: :put, class: "btn btn-danger" %>
		</center>
</div>

app/views/members/edit.html.erb
<div class="row">
	<div class="col-xs-offset-1 col-xs-9">
		<h2 class="page-title">登録情報編集
		<%= link_to "退会する", delete_me_path, class: "btn btn-danger" %></h2>
	</div>
</div>


<div class="row">
	<div class="col-xs-offset-1 col-xs-9">

	<%= form_for(@member) do |f| %>
	<table class="table table-bordered">
		<thead>
			<tr>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th class="active">氏名</th>
				<td><%= f.text_field :first_name %><%= f.text_field :last_name %></td>
			</tr>
			<tr>
				<th class="active">カナ</th>
				<td><%= f.text_field :first_name_kana %><%= f.text_field :last_name_kana %></td>
			</tr>
			<tr>
				<th class="active">郵便番号</th>
				<td>〒<%= f.text_field :postal_code %>(ハイフン必須)</td>
			</tr>
			<tr>
				<th class="active">住所</th>
				<td><%= f.text_field :address, :size=>"50" %></td>
			</tr>
			<tr>
				<th class="active">電話番号</th>
				<td><%= f.text_field :phone %>(ハイフン不要)</td>
			</tr>
			<tr>
				<th class="active">メールアドレス</th>
				<td><%= f.email_field :email, :size=>"50" %></td>
			</tr>
		</tbody>
	</table>
	<%= f.submit "編集内容を保存する",class: "btn btn-primary center-block" %>
	<% end %>
	</div>
</div>

app/views/members/show.html.erb
<div class="row">

	<div class="col-xs-offset-1 col-xs-9">
		<h1 class="page-title">マイページ</h1>
	</div>
</div>

<div class="row">
	<div class="col-xs-offset-1 col-xs-10">

		<div class="page-info"><h2>登録情報</h2></div>

		<div class="member-btn">
			<%= link_to "編集する", edit_member_path(current_member),class: "btn btn-primary" %>
			<%= link_to "パスワードを変更する", new_member_password_path(current_member),class: "btn btn-warning" %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-offset-1 col-xs-10">

	<table class="table table-bordered">
		<thead>
			<tr>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th class="active">氏名</th>
				<td><%= @member.first_name %><%= @member.last_name %></td>
			</tr>
			<tr>
				<th class="active">カナ</th>
				<td><%= @member.first_name_kana %><%= @member.last_name_kana %></td>
			</tr>
			<tr>
				<th class="active">郵便番号</th>
				<td><%= @member.postal_code %></td>
			</tr>
			<tr>
				<th class="active">住所</th>
				<td><%= @member.address %></td>
			</tr>
			<tr>
				<th class="active">電話番号</th>
				<td><%= @member.phone %></td>
			</tr>
			<tr>
				<th class="active">メールアドレス</th>
				<td><%= @member.email %></td>
			</tr>
		</tbody>
	</table>
	</div>
</div>

<div class="row">
	<div class="col-xs-offset-1 col-xs-10">
		<table class="member-menu" width="200">
			<thead>
				<tr>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th><h4>配送先</h4></th>
					<td><%= link_to "一覧を見る", shipping_addresses_path(current_member),class: "btn btn-info" %></td>
				</tr>
				<tr>
					<th><h4>注文履歴</h4></th>
					<td><%= link_to "一覧を見る", orders_path(current_member),class: "btn btn-info" %></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/members/update.html.erb
<h1>Members#update</h1>
<p>Find me in app/views/members/update.html.erb</p>